### PR TITLE
Librairies -> Libraries (fixed spelling error)

### PR DESCRIPTION
**Pull request by ModEngineer**
Make sure to also copy this to the docs at http://pewpew.live/documentation/main.html

### CODE REVIEW

**Comment by jyaif** [comment]
Thanks!

> Make sure to also copy this to the docs at http://pewpew.live/documentation/main.html

I'm going to deprecate the old doc website and make it point to https://jyaif.github.io/ppl-utils/ instead.

**Comment by ModEngineer** [comment]
That'll also lower the amount of network traffic/bandwidth you'll need.

**Comment by jyaif** [comment]
Rebased the commit. Thanks!

**Comment by ModEngineer** [comment]
Alright, I'm removing my fork of the repo.

**Pull request merged**
